var personal = {
    myname:       "",
    myfirstname:  "",
    mylastname:   "",
    myaddress:    "",
    mystreet:     "",
    mysuburb:     "",
    mystate:      "",
    mypostcode:   "",
    shipito:
    {
        myaddress:    "",
        mystreet:     "",
        mysuburb:     "",
        mystate:      "",
        mypostcode:   "",
        mycountry:    "",
    },
    shipito_eu:
    {
        myaddress:    "",
        mystreet:     "",
        mysuburb:     "",
        mystate:      "",
        mypostcode:   "",
        mycountry:    "",
    },
    myphone:      "",
    mymobile:     "",
    mymasterpw:   "",
    myemail:      "",
    myemail2:     "",
    mybankurl:    "",
    mycreditcard: "",
    myopenexchangeratesappid: "",
    mycurrencyconverterapikey: "",
}
