var personal = {
    myname:       "",
    myfirstname:  "",
    mylastname:   "",
    myaddress:    "",
    mystreet:     "",
    mysuburb:     "",
    myphone:      "",
    mypostcode:   "",
    mymasterpw:   "",
    myemail:      "",
    myemail2:     "",
    mybankurl:    "",
    mycreditcard: "",
}
